import assert from "node:assert";

export function errors() {
  try {
    throw "foobar";
  } catch (err) {
    console.log(err);
  } finally {
    console.log("finally");
  }
}
